remote_theme: raviriley/agency-jekyll-theme

url    : "https://keysetsu.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : KEY
email      : kenichi.yosh@gmail.com #this is also the email contact forms will go to
description: My short portfolio as an ecommerce product lister / automation scripter.
author     : Kenichi Yoshida
#logo       :
#  path       : assets/img/logo.png
  # height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/mdawrrvb"

plugins:
  - jekyll-remote-theme
