url: ""
baseurl: ""

# Site settings
title: KEY
email: kenichi.yosh@gmail.com
description: 


# Team names, titles and social links
people:
- name: Kenichi Yoshida
  pic: 1
  position: Product Lister / Programmer
  bio: I am a product lister and programmer. I have experience in listing products on e-commerce platforms such as Amazon, eBay, and Shopify. I also have experience in programming languages such as Python, JavaScript, and HTML/CSS. I am passionate about creating efficient and user-friendly solutions for online businesses.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: http://github.com/keysetsu

# Postal address (add as many lines as necessary)
address:
  - line: 50 Captain Musni St.,
  - line: Brgy. Santa Ana, Pateros,
  - line: Metro Manila, Philippines, 1621

# Build settings
markdown: kramdown
permalink: pretty
